
package com.thinkgem.jeesite.modules.wsinterface.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSIService", targetNamespace = "http://www.ssii.com.cn")
@XmlSeeAlso({
    cn.com.ssii.ObjectFactory.class,
    com.ssii.ObjectFactory.class
})
public interface WSIService {


    /**
     * 
     * @param laStoreHourseStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendLaStoreHouse", targetNamespace = "http://www.ssii.com.cn", className = "cn.com.ssii.SendLaStoreHouse")
    @ResponseWrapper(localName = "sendLaStoreHouseResponse", targetNamespace = "http://www.ssii.com.cn", className = "cn.com.ssii.SendLaStoreHouseResponse")
    public String sendLaStoreHouse(
        @WebParam(name = "laStoreHourseStr", targetNamespace = "http://www.ssii.com/")
        String laStoreHourseStr);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://www.ssii.com.cn", className = "cn.com.ssii.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://www.ssii.com.cn", className = "cn.com.ssii.AuthResponse")
    public boolean auth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
